import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='bg-base-100 text-base-content min-h-screen flex flex-col items-center justify-center p-4'
      >
        <Toaster position="top-left"/>
         {/* Header */}
      <div className="navbar bg-base-100 shadow-md justify-evenly">
        <div className="">
          <h1 className="text-2xl font-bold pl-4">Darts Tournaments</h1>
        </div>
        <div className="">
          <Link href="/" className="btn btn-ghost normal-case text-md">
            Főoldal
          </Link>
          <Link href="/search" className="btn btn-ghost normal-case text-md">
            játékos keresés
          </Link>
        </div>
      </div>
        {children}
      </body>
    </html>
  );
}
